name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        source_dir: .
        container_name: $web
        connection_string: ${{secrets.BlobConnectionString}}
